// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDrLzq5WuMMXMwWTFcWUaZATeIHm4_9ao',
    appId: '1:466207815643:web:fa8987aa27c23b835c99fe',
    messagingSenderId: '466207815643',
    projectId: 'doctor-appointment-app-15aa9',
    authDomain: 'doctor-appointment-app-15aa9.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-15aa9.appspot.com',
    measurementId: 'G-HLFTLNYHXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXWsmTBUyuKBbAvaXt7eJD0ZubV5kR0AA',
    appId: '1:466207815643:android:68a3934fc5deb16b5c99fe',
    messagingSenderId: '466207815643',
    projectId: 'doctor-appointment-app-15aa9',
    storageBucket: 'doctor-appointment-app-15aa9.appspot.com',
  );
}
